Server side oauth
codex-team/electon.editor pull request #102
Opened 2017-12-27 04:15 UTC by gohabereg

2017-12-27 04:32 UTC, neSpecc requested changes

2017-12-27 04:32 UTC, neSpecc commented on src/controllers/auth.js
> +    let webContents = window.webContents;
надо описать и приложить ссылку на документацию

2017-12-27 04:32 UTC, neSpecc commented on src/controllers/auth.js
> +            event.returnValue = false;
сюда надо сразу лог поставить

2017-12-29 21:41 UTC, neSpecc approved these changes

2017-12-29 21:47 UTC, talyguryn requested changes

2017-12-29 21:47 UTC, talyguryn commented on src/controllers/auth.js
> +    /** Fires when popup page is refreshed
```
/**
 * Fires

2017-12-29 21:47 UTC, talyguryn commented on src/controllers/auth.js
> +      'scope=email profile' +
пробелы можно? обработает?

2017-12-29 21:47 UTC, talyguryn commented on src/controllers/auth.js
> +    window.loadURL('https://accounts.google.com/o/oauth2/v2/auth?' +
в константу можно вынести?

2017-12-29 21:47 UTC, talyguryn commented on src/controllers/auth.js
> +      'scope=email profile' +
это можно собрать из не конкатенацией строки?

2017-12-29 21:48 UTC, gohabereg commented on src/controllers/auth.js
> +      'scope=email profile' +
Можно

2017-12-29 21:48 UTC, gohabereg commented on src/controllers/auth.js
> +    window.loadURL('https://accounts.google.com/o/oauth2/v2/auth?' +
Не вижу смысла

2017-12-29 21:48 UTC, gohabereg commented on src/controllers/auth.js
> +      'scope=email profile' +
Чем тебе конкатенация не угодила?

2017-12-29 22:20 UTC, neSpecc requested changes

2017-12-29 22:20 UTC, neSpecc commented on src/controllers/auth.js
> +          try {
лучше добавить .catch у промиса.

2017-12-29 22:35 UTC, talyguryn approved these changes

2017-12-30 12:01 UTC, neSpecc approved these changes

2017-12-30 19:06 UTC, talyguryn approved these changes

2017-12-30 19:06 UTC, merged