Requests authorization
codex-team/electon.editor pull request #103
Opened 2018-01-03 20:39 UTC by gohabereg

2018-01-03 20:44 UTC, neSpecc requested changes

2018-01-03 20:44 UTC, neSpecc commented on src/controllers/auth.js
> +          user.name = payload.name;
может это все в конструктор передать лучше?

2018-01-03 20:44 UTC, neSpecc commented on src/controllers/syncObserver.js
> +        Authorization: 'Basic ' + global.user.token,
а что такое Basic? надо бы описать в комментах

2018-01-04 09:53 UTC, talyguryn approved these changes

2018-01-05 13:45 UTC, neSpecc approved these changes

2018-01-05 13:49 UTC, merged