Save auth status
codex-team/electon.editor pull request #117
Opened 2018-01-17 15:20 UTC by gohabereg

2018-01-17 15:29 UTC, neSpecc requested changes

2018-01-17 15:29 UTC, neSpecc commented on src/models/user.js
> +    ipcMain.on('user - get', (event) => {
это лучше перенести в контроллер.

2018-01-17 15:29 UTC, neSpecc commented on src/models/user.js
> +        this.id = user._id;
это можно перенести в сеттер data, по аналогии с другими моделями. Тогда уберется такой же кусок в update

2018-01-17 15:29 UTC, neSpecc commented on src/models/user.js
> +     */
табуляция

2018-01-17 16:26 UTC, neSpecc commented on src/models/user.js
> +   * @param {Object} userData
можно сверху определить  `@typeded {object} userData ` , чтобы использовать его можно было переиспользовать

2018-01-17 20:30 UTC, talyguryn requested changes

2018-01-17 20:30 UTC, talyguryn commented on src/models/user.js
> +          name: this.name,
сервер ещё и мыло отдает. не хочешь и его сохранить?

2018-01-17 21:14 UTC, talyguryn approved these changes

2018-01-18 12:21 UTC, neSpecc requested changes

2018-01-18 12:21 UTC, neSpecc commented on src/controllers/auth.js
> +      if (process.env.GOOGLE_REDIRECT_URI !== path) return;
тут надо добавить логирование ошибки

2018-01-18 12:21 UTC, neSpecc commented on src/models/user.js
> +          name: this.name,
да, email нужен. Лучше вообще все сохранять, чтобы API играло роль синхронизации, а не хранения

2018-01-18 12:23 UTC, gohabereg commented on src/controllers/auth.js
> +      if (process.env.GOOGLE_REDIRECT_URI !== path) return;
Это не ошибка

2018-01-18 15:05 UTC, neSpecc approved these changes

2018-01-18 15:06 UTC, merged