Log out capable
codex-team/electon.editor pull request #121
Opened 2018-01-23 18:41 UTC by khaydarov

2018-01-23 20:57 UTC, neSpecc requested changes
При логауте надо:
- Отправить `sync mutation`, чтобы залить все локальные данные в облако
- После этого очистить локальную базу (папки/статьи)
- Если интернета нет, то проверить, есть ли несинхронизированные изменения (см `syncObserver#prepareUpdates`). Если есть, показать системное предупреждение `You have 2 notes that was not syncronized yet. They will be lost after logout, because you have not connected to the Network. Are you sure to continue?` (Continue/Cancel)

2018-01-25 15:49 UTC, gohabereg approved these changes

2018-01-25 17:51 UTC, talyguryn approved these changes

2018-01-25 17:56 UTC, n0str approved these changes

2018-01-25 18:33 UTC, neSpecc requested changes

2018-01-25 18:33 UTC, neSpecc commented on src/controllers/auth.js
> +        if (!connection && hasUpdates) {
hasUpdates не асинхронный

2018-01-25 18:33 UTC, neSpecc commented on src/controllers/auth.js
> +                buttons: ['No', 'Yes'],
'Cancel', 'Continue'

2018-02-01 22:17 UTC, neSpecc requested changes

2018-02-01 22:17 UTC, neSpecc commented on src/codex-notes.js
> -         * @type {SyncObserver}
по моему, type указывался чтобы шторм подсвечивал функции при обращении через glopal.app.syncObserver, проверь, работает ли без этого

2018-02-01 22:17 UTC, neSpecc commented on src/controllers/auth.js
> +          if (!global.app.syncObserver) {
к этому моменту нужно написать комментарий, чтобы не забыть через пол года зачем это делается

2018-02-01 22:17 UTC, neSpecc commented on src/controllers/auth.js
> +          if (updates.folders.length === 0 && !updates.notes) {
notes должны тоже быть массивом и проверяться через length. Либо фолдеры должны быть null вместо []. В общем, это надо делать как-то однообразно

2018-02-01 22:17 UTC, neSpecc commented on src/controllers/auth.js
> +   *
описание

2018-02-01 22:17 UTC, neSpecc commented on src/controllers/syncObserver.js
> +    console.log("API req", this.api);
лишний лог

2018-02-01 22:17 UTC, neSpecc commented on src/utils/database.js
> +    return Promise.all(sequence);
можно с помощью `.then((resp) => {})` залогировать количество удаленных документов. В `resp` попадет массив из return-value (`err, numRemoved`) каждого промиса

2018-02-03 12:54 UTC, neSpecc requested changes

2018-02-03 12:54 UTC, neSpecc commented on src/codex-notes.js
> +          this.syncObserver.on('sync', (data) => {
after logout and re-loging, this subscription will be lost

2018-02-06 15:20 UTC, closed without merging