save avatar to client
codex-team/electon.editor pull request #125
Opened 2018-02-01 12:41 UTC by Nikitos9I

2018-02-01 14:58 UTC, gohabereg requested changes

2018-02-01 14:58 UTC, gohabereg commented on src/models/user.js
> +      .then(request(uri).pipe(fs.createWriteStream(filename)).on('close', function(){
Что тут написано?
Можно как-то разнести это до читаемого вида?

2018-02-01 14:58 UTC, gohabereg commented on src/models/user.js
> +    rp.head(uri)
Зачем нужен этот запрос?

2018-02-01 15:02 UTC, gohabereg requested changes
И нужно пересохранять путь в модели, чтобы картинка подгружалась с локали

2018-02-01 15:02 UTC, gohabereg commented on src/models/user.js
> +        filename = 'assets/icons/avatars/' + this.name + '.jpeg';
Лучше сохраняй с каким-нибудь статическим названием. Всего один пользователь же в один момент времени.

2018-02-01 15:05 UTC, neSpecc requested changes

2018-02-01 15:05 UTC, neSpecc commented on src/models/user.js
> +      rp = require('request-promise');
rp — не понятное название переменной

2018-02-01 15:05 UTC, neSpecc commented on src/models/user.js
> +      request = require('request'),
точно нужны и request и request-promise?

2018-02-01 15:05 UTC, neSpecc commented on src/models/user.js
> +  async save() {
название метода не соответствует тому, что она делает

2018-02-06 18:42 UTC, khaydarov approved these changes

2018-02-07 04:35 UTC, talyguryn commented on src/models/user.js
> +    this.localPhoto = path.join(db.appFolder, 'avatar.jpeg');
```
CodeX Notes runtime error: ReferenceError: path is not defined
    at new User (/Users/talyguryn/GitHub/codex.notes/src/models/user.js:30:23)
    ...
```

2018-02-07 04:36 UTC, talyguryn commented on src/models/user.js
> +    this.localPhoto = path.join(db.appFolder, 'avatar.jpeg');
https://nodejs.org/api/path.html#path_path

2018-02-08 16:31 UTC, gohabereg approved these changes

2018-02-08 17:07 UTC, gohabereg requested changes

2018-02-08 17:07 UTC, gohabereg commented on src/models/user.js
> +      if (err) {
Просто залогируй ошибку, не надо ифы городить

2018-02-08 17:16 UTC, gohabereg approved these changes

2018-02-08 17:22 UTC, neSpecc approved these changes

2018-02-08 17:25 UTC, talyguryn approved these changes

2018-02-08 17:26 UTC, merged