Collaborators
codex-team/electon.editor pull request #138
Opened 2018-02-08 10:31 UTC by gohabereg

1. Save new Collaborator to the database
2. Collaborators sync flow

2018-02-08 11:04 UTC, neSpecc requested changes

2018-02-08 11:04 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +        collaborators = window.ipcRenderer.sendSync('folder - get collaborators', {id});
надо сделать асинхронную подгрузку коллабораторов

2018-02-08 11:04 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +    this.membersList.innerHTML = '';
вынести в метод `showCollaboratos`

2018-02-08 11:04 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +      Dialog.error(result.message ? result.message : 'Error while adding a collaborator to the folder');
`result.message ||  'Error while adding a collaborator to the folder'`

2018-02-08 11:04 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +   * @param collaborator
описание функции, тип и описание параметра

2018-02-08 17:29 UTC, neSpecc commented on public/javascripts/folder.js
> +      this.collaborators = collaborators;
this.collaborators надо объявить в конструкторе

2018-02-08 18:23 UTC, neSpecc requested changes
- [ ] Добавить анимацию `wobble` при вводе невалидного емэила
- [ ] Для неавторизованного пользователя вместо поля ввода почты показывать кнопку Login with Google

<img width="675" alt="screen shot 2018-02-08 at 21 23 31" src="https://user-images.githubusercontent.com/3684889/35990818-56e86d82-0d16-11e8-9728-9c41ed71e2cb.png">

2018-02-13 10:49 UTC, khaydarov requested changes

2018-02-13 10:49 UTC, khaydarov commented on src/models/collaborator.js
> +     *
табуляция 2 пробела (

2018-02-13 10:49 UTC, khaydarov commented on src/models/collaborator.js
> + * @typedef {Object} CollaboratorData
@typedef {CollaboratorData} CollaboratorData - кажется так указывается

2018-02-14 07:34 UTC, neSpecc requested changes

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/app.js
> +  codex.notes.user.authObserver.login(codex.notes.user.userData);
если этот модуль входит в класс User, то инициализация должна быть в конструкторе user. Если он должен быть отдельно, то его надо вынести из user

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/auth-observer.js
> + * @classdesc Store user's auth state
надо более понятно написать, для чего этот модуль используется в приложении

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/auth-observer.js
> +    this.user = null;
для чего тут user?

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/auth-observer.js
> +   * @param user - logged user
не указан тип

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +   * @param collaborator
не описан тип и содержание объекта

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/folder.js
> +      codex.notes.aside.folderSettings.showCollaborators(this.collaborators);
не хватает проверки, открыта ли еще данная папка.

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/user.js
> +    this.authObserver = new AuthObserver({
надо описать предназначение этой части кода

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/user.js
> +    this.userData = window.ipcRenderer.sendSync('user - get');
свойства класса надо описывать в typedef над классом

2018-02-14 07:34 UTC, neSpecc commented on public/javascripts/user.js
>      let authResponse = window.ipcRenderer.sendSync('auth - google auth');
может быть это как-то поместить в authObserver?

2018-02-14 07:34 UTC, neSpecc commented on src/codex-notes.js
> + * AppProtocol Controller
не понятное описание, нужно подробнее

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/app-protocol.js
> + * @classdesc Class to process urls with custom app protocol
to handle URLs with the custom protocol

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/app-protocol.js
> +    console.log('Processing url ', url);
можно убрать лог

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/auth.js
> +      });
перенести сюда `global.app.sockets.leaveChannel(channel);` чтобы канал закрывался при закрытии окна

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/auth.js
> +          global.app.sockets.leaveChannel(channel);
отсюда уберется leaveChannel

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/auth.js
> +        global.app.sockets.leaveChannel(channel);
отсюда уберется leaveChannel

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/auth.js
> +          message: 'You should login with your google account to get access to shared folders'
`with your google account` можно убрать

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/syncObserver.js
> +        return this.sendCollaboratorInvite(collaborator);
это не инвайты, а просто мутация на синхронизацию локальной базы с облаком. Сейчас при каждом запуске отправляются новые письма повторно

2018-02-14 07:34 UTC, neSpecc commented on src/controllers/syncObserver.js
> +      userId: global.user ? global.user.id : null,
тут не может быть null, лучше выкинуть ошибку, если юзера нет

2018-02-14 07:34 UTC, neSpecc commented on src/models/collaborator.js
> + * @typedef {Object} CollaboratorData
нет, это обычный объект. Классы да, надо задавать как свой тип данных

2018-02-14 07:34 UTC, neSpecc commented on src/models/collaborator.js
> +     */
табуляцию надо поправить

2018-02-14 07:34 UTC, neSpecc commented on src/models/collaborator.js
> +     * @param _id
@param {CollaboratorData} collaboratorData

2018-02-14 07:34 UTC, neSpecc commented on src/models/folder.js
> +      collaborators: this.collaborators,
это поле не нужно инсертить в базу, поэтому в методе save нужно удалять его, по аналогии с `notes`, см 208 строку

2018-02-14 07:34 UTC, neSpecc commented on src/models/folder.js
> +      collaborators: this.collaborators,
и не только в ней, еще в паре функций

2018-02-22 16:31 UTC, talyguryn approved these changes

2018-02-22 16:40 UTC, neSpecc approved these changes

2018-02-22 16:47 UTC, khaydarov approved these changes

2018-02-22 16:47 UTC, khaydarov commented on public/build/bundle.css
> +        }
Что с табуляцией?

2018-02-22 17:05 UTC, neSpecc approved these changes

2018-02-22 17:05 UTC, merged