Sockets module base. Get JWT by sockets
codex-team/electon.editor pull request #141
Opened 2018-02-12 11:38 UTC by neSpecc

2018-02-12 14:12 UTC, talyguryn requested changes

2018-02-12 14:12 UTC, talyguryn commented on src/controllers/auth.js
> +      console.log('jwt ->>', jwt);
убери лог

2018-02-12 14:12 UTC, talyguryn commented on src/controllers/sockets.js
> + *  WebSocket implementation.
лишний пробел после *

2018-02-12 14:12 UTC, talyguryn commented on src/controllers/sockets.js
> +  constructor(){
запусти eslint

2018-02-13 11:41 UTC, talyguryn approved these changes

2018-02-13 11:46 UTC, gohabereg approved these changes

2018-02-13 16:07 UTC, merged