shortcut initialisation fixes
codex-team/electon.editor pull request #142
Opened 2018-02-13 11:13 UTC by khaydarov

2018-02-13 16:16 UTC, neSpecc requested changes
- при копировании Тайтл не вставляется
- модуль надо подключить через npm

2018-02-15 15:51 UTC, talyguryn approved these changes

2018-03-07 05:42 UTC, talyguryn commented
Действительно ли нужно ставить пустые строки между параграфами?
Можно ли хоть как-то сохранять заголовки в тексте?

![](https://capella.pics/e85d9524-117b-47ba-9f94-8e3a10891333)
⬇️
![](https://capella.pics/5adf822f-05bc-4dff-91b3-f2ebc655119e)
![](https://capella.pics/8ccec887-8711-4d77-a0f6-80e48a3243b1)

2018-03-07 06:13 UTC, neSpecc approved these changes

2018-03-07 06:21 UTC, merged