Add ava for collaborator
codex-team/electon.editor pull request #144
Opened 2018-02-15 18:15 UTC by talyguryn

2018-02-15 18:19 UTC, khaydarov approved these changes

2018-02-15 21:14 UTC, neSpecc requested changes

2018-02-15 21:14 UTC, neSpecc commented on public/stylesheets/components/folder-settings.css
> +.collaborator-photo {
это должно быть в блоке member-list ->  &__photo

2018-02-15 21:14 UTC, neSpecc commented on src/models/collaborator.js
> +     * @param user
надо задокументировать типы

2018-02-16 10:59 UTC, neSpecc approved these changes

2018-02-16 11:02 UTC, merged