initial commit for show badge issue
codex-team/electon.editor pull request #149
Opened 2018-02-27 17:27 UTC by khaydarov

2018-02-27 17:57 UTC, neSpecc requested changes

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +    this.visits = new Visits();
комментарий

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +      await this.visits.syncVisits();
комментарий

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +          if ( this.visits.visitedNotes[note._id] >= note.dtModify ) {
this.visits.getDate(note._id)

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +            note.visited = true;
note.is_read = true

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +          if ( this.visits.visitedNotes[note._id] >= note.dtModify ) {
не обрабатывается отсутствие статьи в visits

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +          if ( this.visits.visitedNotes[note._id] >= note.dtModify ) {
перенести в модель NotesList в свойство isSeen

2018-02-27 17:57 UTC, neSpecc commented on src/models/visits.js
> +class Visits {
SeenStateObserver

2018-02-27 17:57 UTC, neSpecc commented on src/controllers/notes.js
> +      notesInFolder.forEach( async (note) => {
подгружать индикаторы isSeen отдельным запросом после открытия папки, передав ids статей

2018-03-13 18:00 UTC, neSpecc requested changes

2018-03-13 18:00 UTC, neSpecc commented on public/javascripts/folder.js
> +    window.ipcRenderer.once('notes - seen', (event, {data}) => {
надо описать {data}

2018-03-13 18:00 UTC, neSpecc commented on src/controllers/notes.js
> +      let seenNotes = await this.SeenStateObserver.getSeenNotes(noteIds);
вынести логику в обработчик  `this.markAsSeen();`

2018-03-13 18:00 UTC, neSpecc commented on src/controllers/notes.js
> +      this.SeenStateObserver.touch(note.data.id);
перенести логику в обработчик this.saveNote

2018-03-13 18:00 UTC, neSpecc commented on src/controllers/notes.js
> +      this.SeenStateObserver.touch(id);
перенести логику в обработчик

2018-03-15 21:17 UTC, neSpecc requested changes

2018-03-15 21:17 UTC, neSpecc commented on public/javascripts/folder.js
> +
зачем убран todo? он еще актуален

2018-03-15 21:17 UTC, neSpecc commented on public/javascripts/folder.js
> +    this.notes.forEach( (note) => {
```js
let noteIds = this.notes.map(note => note._id);
```

2018-03-15 21:17 UTC, neSpecc commented on public/javascripts/folder.js
> +     *     Ex: data[ noteId ] = lastSeen - timestamp of last seen
эти две строчки комментов оформлены не по jsdoc

2018-03-15 21:17 UTC, neSpecc commented on src/controllers/notes.js
> +      // make "seen" edited note
mark editen Note as seen

2018-03-15 21:17 UTC, neSpecc commented on src/controllers/notes.js
> +   * Get's information about note visits and emits the event
> about note visits

about seen-state of passed notes

2018-03-15 21:17 UTC, neSpecc commented on src/controllers/notes.js
> +        data: seenNotes
data не лучшее название в данном случае (я долго пытался понять код клиента), лучше назвать seenIds.

2018-03-15 21:17 UTC, neSpecc commented on src/models/seenStateObserver.js
> + * Checks seen notes or makes notes "seen"
Manipulates seen-state of Notes

2018-03-15 21:17 UTC, neSpecc commented on src/models/seenStateObserver.js
> + * @property this.getSeenNotes {Function} - returns information about passed note
this не нужно. тип ставится перед названием 😟

2018-03-15 21:17 UTC, neSpecc commented on src/models/seenStateObserver.js
> +     * @param noteId {Number} - note id
тип перед названием

2018-03-15 21:19 UTC, neSpecc commented on src/controllers/notes.js
> +        data: seenNotes
и вообще data — всегда плохое название

2018-03-20 07:24 UTC, talyguryn requested changes

2018-03-20 07:24 UTC, talyguryn commented on src/models/seenStateObserver.js
> +            response[note.noteId] = note.lastSeen;
есть подозрение, что у тебя не работает линтер

2018-03-20 07:24 UTC, talyguryn commented on src/models/seenStateObserver.js
> +        await db.update(db.VISITS, query, {
из параметров нужно вынести объекты в переменные

2018-03-20 07:26 UTC, khaydarov commented on src/models/seenStateObserver.js
> +        await db.update(db.VISITS, query, {
какая разница? плодить лишние переменные - выделять память под них, а в вызове объект тут же очистится

2018-03-20 19:15 UTC, talyguryn approved these changes

2018-03-20 19:15 UTC, neSpecc approved these changes
👍

2018-03-20 19:15 UTC, merged