SortNotesList
codex-team/electon.editor pull request #164
Opened 2018-04-03 16:39 UTC by Nikitos9I

updated notes.js
added env.js

2018-04-03 16:41 UTC, gohabereg requested changes

2018-04-03 16:41 UTC, gohabereg commented on src/controllers/notes.js
> +    notesList.sort(function(leftValue, rightValue) {
(a, b) => a.dtModify - b.dtModify

2018-04-03 16:44 UTC, gohabereg requested changes

2018-04-03 16:44 UTC, gohabereg commented on src/controllers/notes.js
> +  async sortNotesList(notesList) {
async не нужен

2018-04-03 16:44 UTC, gohabereg commented on src/controllers/notes.js
> +   * @returns {Object} sorted list of notes
Функция ничего не возвращает

2018-04-03 16:44 UTC, gohabereg commented on src/controllers/notes.js
> +   * @returns {Object} sorted list of notes
Но это не очень хорошо. Поэтому лучше сделать `notesList.slice().sort(...)`

2018-04-03 19:06 UTC, talyguryn approved these changes

2018-04-04 07:03 UTC, khaydarov approved these changes

2018-04-05 17:30 UTC, gohabereg approved these changes

2018-04-05 19:05 UTC, neSpecc approved these changes

2018-04-05 19:07 UTC, merged