Push Notifications
codex-team/electon.editor pull request #165
Opened 2018-04-09 10:52 UTC by khaydarov

2018-04-09 10:56 UTC, neSpecc requested changes

2018-04-09 10:56 UTC, neSpecc commented on src/controllers/pushNotifications.js
> +        options.sound = 'path to file';
некорректный дефолтный путь.

2018-04-09 10:56 UTC, neSpecc commented on src/controllers/pushNotifications.js
> + * @property {Boolean} silent - need sound or not
какое значение `silent` по дефолту?

2018-04-09 10:56 UTC, neSpecc commented on src/controllers/pushNotifications.js
> +        notification.show();
а как задать ссылку, которая откроется при клике на уведомление? чтобы можно было попасть в конкретную статью

2018-04-25 11:39 UTC, neSpecc requested changes

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/note.js
> +    this.hashedNote = null;
не описано свойство

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/note.js
> +        if (currentHashedNote === this.hashedNote) {
надо описать смысловую часть кода

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/note.js
> +          return;
и добавить лог, что ничего не изменилось

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/note.js
> +        // save client performed JSON stringify
надо написать, не что делается, а для чего

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/note.js
> +     */
для того, чтобы ...

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/utils/hashCoder.js
> +  static simpleHash(text) {
два раза слово хэш. Зачем нужен simple, если других методов тут нет и врятли будут

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/utils/hashCoder.js
> +let memoizedHashes = {};
cachedHashes

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/utils/hashCoder.js
> +    memoizedHashes[text] = hash;
гигантские ключи у объекта. Надо изучить, эффективнее ли это чем Array.find

2018-04-25 11:39 UTC, neSpecc commented on public/javascripts/utils/hashCoder.js
> +    memoizedHashes[text] = hash;
и этот объект нигде не очищается, то есть за 10 минут работы в приложении там будет громадный объект и утечка памяти

2018-04-25 11:39 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +    let notification;
надо задокументировать

2018-04-25 11:39 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +   * @param {object} message.sender
не хватает описания

2018-04-25 11:39 UTC, neSpecc commented on src/controllers/notes.js
> +        content: noteData.data.content || JSON.stringify(noteData.data.items),
не описанный момент, надо как-то прозрачнее сделать

2018-05-10 15:24 UTC, neSpecc requested changes

2018-05-10 15:24 UTC, neSpecc commented on public/javascripts/aside.js
> +      if (note._id === codex.notes.note.currentNoteId) {
add description comment

2018-05-10 15:24 UTC, neSpecc commented on public/javascripts/note.js
> +    this.currentNoteId = null;
describe in docs

2018-05-10 15:24 UTC, neSpecc commented on public/javascripts/note.js
> +        /** note is not saved because hashes are similar */
Note won't be saved because...

2018-05-10 15:24 UTC, neSpecc commented on public/javascripts/note.js
> +         * JSON.stringify is not saving the order of objects so on backend side content might be different
We should use client-side stringifying because on the server-side it can generate different string caused of unmatched order of object properties

2018-05-10 15:24 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +      this.sync(true);
pass options with destructor

2018-05-10 15:24 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +   * @param {boolean} getDataFromCloud
isNeedToLoadDataFromCloud

2018-05-10 15:24 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +   * @param {boolean} getDataFromCloud
and describe

2018-05-10 15:24 UTC, neSpecc commented on src/controllers/cloudSyncObserver.js
> +      // return dataFromCloud;
is it safe?

2018-05-10 15:24 UTC, neSpecc commented on src/controllers/pushNotifications.js
> +     * @param {PushCallbacks} callbacks
describe

2018-05-10 18:13 UTC, talyguryn approved these changes

2018-05-10 18:14 UTC, neSpecc approved these changes

2018-05-11 09:24 UTC, neSpecc requested changes

2018-05-11 09:24 UTC, neSpecc commented on src/controllers/pushNotifications.js
> +        notification.on('click', callbacks['click']);
надо добавить проверку на наличие callbacks['click']

2018-05-14 14:04 UTC, neSpecc approved these changes

2018-05-14 14:06 UTC, merged