fixed
codex-team/electon.editor pull request #166
Opened 2018-04-12 20:30 UTC by Nikitos9I

bug with notes and folders fixed

2018-04-12 20:34 UTC, gohabereg requested changes

2018-04-12 20:34 UTC, gohabereg commented on public/javascripts/note.js
>       * If folder is opened, pass id. Otherwise pass false
`null` же, а не `false`

2018-04-12 20:34 UTC, gohabereg commented on public/javascripts/note.js
> +    if (!this.folderId) this.folderId = codex.notes.aside.currentFolder? codex.notes.aside.currentFolder.id: null;
пробельчики пожалуйста

2018-04-12 20:34 UTC, gohabereg commented on public/javascripts/note.js
> +    let folderId = this.folderId;
зачем эта переменная?

2018-04-12 20:34 UTC, gohabereg commented on public/javascripts/note.js
>          let saveIndicator = document.getElementById('save-indicator');
Замени на  `$.get('save-indicator')` плз

2018-04-13 19:51 UTC, talyguryn approved these changes

2018-04-16 07:18 UTC, merged