SyncQueue for preparing changes
codex-team/electon.editor pull request #167
Opened 2018-04-17 21:08 UTC by khaydarov

2018-04-21 16:41 UTC, talyguryn requested changes

2018-04-21 16:41 UTC, talyguryn commented on src/codex-notes.js
> +const SyncQueueObserver = require('./controllers/SyncQueueObserver');
`./controllers/SyncQueueObserver` -> `./controllers/syncQueueObserver`

2018-04-21 16:41 UTC, talyguryn commented on src/controllers/syncQueueObserver.js
> + * @class SeenStateObserver
syncQueueObserver

2018-04-21 16:41 UTC, talyguryn commented on src/controllers/syncQueueObserver.js
> + * @module SyncQueueObserver
syncQueueObserver

2018-04-21 16:41 UTC, talyguryn commented on src/controllers/syncQueueObserver.js
> +
пройдись по файлам линтером

2018-04-21 16:41 UTC, talyguryn commented on src/controllers/syncQueueObserver.js
> +   * @param entityType
тип, описание?

2018-04-25 11:13 UTC, neSpecc requested changes

2018-04-25 11:13 UTC, neSpecc commented on src/controllers/syncQueueObserver.js
> +   * @param modelType
не описан метод и параметр

2018-04-25 11:13 UTC, neSpecc commented on src/models/folder.js
> +  static get syncModelType() {
syncableType

2018-04-25 11:13 UTC, neSpecc commented on src/models/folder.js
> +    return 2;
выглядит харкодом. Как узнать что такой тип не используется в других моделях?

2018-04-25 11:13 UTC, neSpecc commented on src/models/note.js
> +  static async prepareUpdates() {
их не обязательно имплементить внутри потомков, они и так должны быть доступны

2018-04-25 11:13 UTC, neSpecc commented on src/models/syncable.js
> +
надо задать абстрактный геттер sincableType (который у тебя сейчас syncModelType), и в jsdoc пометить его как `@abstract`

2018-04-25 11:13 UTC, neSpecc commented on src/models/syncable.js
> +      return this.get( data.entityId );
нигде не указано что у потомка обязательно должен быть определенный метод `get`. То есть для него тоже нужно сделать абстрактный прототип, который будет выбрасывать ошибку, если его не переопределить в потомке.

```js
/**
 * Return syncable entity's data by id. 
 * Method should be implemented by inheritor.
 *
 * @abstract
 * @param {string} id - syncable entity's id
 * @return {object}
 */
static async get(id){
      throw new Error('Syncable data loader must be implemented by subclass');
}
```

2018-04-25 11:13 UTC, neSpecc commented on src/models/syncable.js
> +          return model.data;
то же самое с геттером `data`

2018-04-26 16:53 UTC, neSpecc requested changes

2018-04-26 16:53 UTC, neSpecc commented on src/controllers/syncQueueObserver.js
> + * Manipulates with entity Queue
with synchronisation queue.

2018-04-26 16:53 UTC, neSpecc commented on src/models/folder.js
> +   * @return {number}
добавить описание

2018-04-26 16:53 UTC, neSpecc commented on src/models/note.js
> +   * @return {number}
описание

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncQueue.js
> +  async save() {
add

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncQueue.js
> +   * @return {Promise.<Array[SyncQueueData]>}
Promise.<SyncQueueData[]>

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncQueue.js
> +  static async getAll( entityType ) {
описать параметр

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncable.js
> +   * @return {Promise.<void>}
она не void возвращает

2018-04-26 16:53 UTC, neSpecc commented on src/controllers/syncQueueObserver.js
> +class syncQueueObserver {
избыточный класс

2018-04-26 16:53 UTC, neSpecc commented on src/controllers/syncQueueObserver.js
> +    let queueObject = new SyncQueue( queueData );
не логичная конструкция

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncQueue.js
> +class SyncQueue {
SincableItem

2018-04-26 16:53 UTC, neSpecc commented on src/models/syncable.js
> + * Models must be getters "data" that returns object with syncable data.
must implement getters data, sincableType

2018-05-04 09:44 UTC, neSpecc requested changes

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncableItem.js
> +    return !(this.data.type === '' || this.data.entityId === '') ;
не учитываются undefined и null, лучше просто написать 
```js
return !this.data.type || !this.data.entityId;
```

2018-05-04 09:44 UTC, neSpecc commented on src/controllers/syncQueue.js
> +    let queueObject = new SyncableItem( queueData );
надо написать в комментах, зачем используется этот класс

2018-05-04 09:44 UTC, neSpecc commented on src/controllers/syncQueue.js
> +   * @return {Promise.<Array[SyncQueueData[]]>}
не понятное указание типа возворащаемого значение

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncable.js
> +  /**
абстрактного `syncableType` все еще нет

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncable.js
> +   * @return {Array[]}
массив массивов? вот тут пример как документируются массивы 

http://usejsdoc.org/tags-param.html

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncable.js
> +   * Get from queue updated Entities
Get changed items from the Sync Queue

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncable.js
> + * Models must implement getters data according to the syncableType that returns object with syncable data.
я бы списком описал что должен заимплементить потомок:
- static getter syncableType
- getter data
- method `get()`
...

2018-05-04 09:44 UTC, neSpecc commented on src/models/syncableItem.js
> + * @typedef {Object} SyncQueueData
нужно понятно описать предназначение класса. Сейчас оно не очень очевидно

2018-05-04 09:44 UTC, neSpecc commented on src/controllers/notes.js
> +      global.app.syncQueue.add( {
а у Folder не нужен add?

2018-05-04 09:51 UTC, neSpecc commented on src/models/syncableItem.js
> +    return !(this.data.type === '' || this.data.entityId === '') ;
вернее наоборот 
```js
return this.data.type && this.data.entityId;
```

2018-05-07 16:15 UTC, talyguryn approved these changes

2018-05-07 17:25 UTC, neSpecc approved these changes

2018-05-07 17:25 UTC, merged