Autoupdater initial
codex-team/electon.editor pull request #169
Opened 2018-04-20 17:48 UTC by talyguryn

2018-04-20 18:16 UTC, gohabereg approved these changes

2018-04-25 09:24 UTC, neSpecc requested changes
- исправить комментарии
- приложить doc с инструкцией по загрузке билдов
- сделать кастомную неблокирующую панель с предложением перезагрузить приложение

2018-04-25 09:24 UTC, neSpecc commented on src/codex-notes.js
> +const updater = require('./updater');
задокументировать объект

2018-04-25 09:24 UTC, neSpecc commented on src/codex-notes.js
> +  checkForUpdates() {
задокументировать метод

2018-04-25 09:24 UTC, neSpecc commented on src/codex-notes.js
> +          message: `CodeX Notes v${info.version} has been downloaded. Restart the application to apply the updates.`,
расхардкодить название

2018-04-25 09:24 UTC, neSpecc commented on src/codex-notes.js
> +          message: `CodeX Notes v${info.version} has been downloaded. Restart the application to apply the updates.`,
номер версии ни о чем не говорит, нужно написать что это новая версия.;

> The new version is available. Restart CodeX Notes to enjoy a new experience.

2018-05-15 16:42 UTC, neSpecc approved these changes

2018-05-15 17:18 UTC, merged