added offline + avatar without google sync
codex-team/electon.editor pull request #82
Opened 2017-12-05 17:37 UTC by Nikitos9I

2017-12-10 14:58 UTC, khaydarov requested changes

2017-12-10 14:58 UTC, khaydarov commented on public/svg/avatar.svg
> +</g>
https://jakearchibald.github.io/svgomg/ - загрузи свг на этот сайт чтобы сжать

2017-12-10 15:03 UTC, neSpecc requested changes

2017-12-10 15:03 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +        .status-panel {
не по бэму

2017-12-10 15:03 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +        display: block;
див и так блочный

2017-12-10 15:03 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +        font-family: Helvetica;
откуда такой шрифт?

2017-12-10 15:03 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +        height: 114px;
не нужно хардкодить высоту и ширину

2017-12-10 15:03 UTC, neSpecc commented on src/views/aside.pug
> +            span.intro_auth
не по бэму

2017-12-10 15:03 UTC, neSpecc commented on src/views/aside.pug
> +            div.auth-button(id="js-auth-button")
не по бэму,
див будет по умолчанию

2017-12-10 15:03 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +        position: relative;
у этой панели абсолютное позиционирование

2017-12-10 15:03 UTC, neSpecc commented on src/views/aside.pug
> +        .aside__authorization
не по бэму

2017-12-10 15:03 UTC, neSpecc commented on src/views/aside.pug
> +        .aside__authorization
я бы не вкладывал эту панель в __avatar

2017-12-28 13:14 UTC, Nikitos9I commented on public/svg/avatar.svg
> +</g>
он не работает

2017-12-28 13:25 UTC, neSpecc requested changes

2017-12-28 13:25 UTC, neSpecc commented on public/stylesheets/components/aside.css
> +                .aside__header-avatar-inner {
это надо отсюда вынести и написать
`&:hover &-inner {}`

2017-12-28 13:25 UTC, neSpecc commented on src/views/aside__header.pug
> +        span.status-panel
почему спан ?

2017-12-28 13:25 UTC, neSpecc commented on src/views/aside__header.pug
> +            span.aside__authorization-title
почему спан ? это же блочный элемент

2017-12-28 16:28 UTC, khaydarov approved these changes

2017-12-28 17:35 UTC, neSpecc approved these changes

2017-12-28 17:37 UTC, talyguryn approved these changes

2017-12-28 17:38 UTC, merged