Invite a new member to the folder
codex-team/electon.editor pull request #83
Opened 2017-12-07 16:43 UTC by talyguryn

2017-12-07 17:10 UTC, gohabereg requested changes

2017-12-07 17:10 UTC, gohabereg commented on controllers/directory.js
> +    ipcMain.on('folder - collaborator add', (event, {id, email}) => {
add collaborator?

2017-12-07 17:10 UTC, gohabereg commented on models/directory.js
> +      // TODO send API request
`@todo  ...`

2017-12-07 17:10 UTC, gohabereg commented on public/javascripts/folder-settings.js
> +        email = input.value.trim(),
Можем как-нибудь проверять, корректен ли email?

2017-12-08 05:54 UTC, neSpecc requested changes

2017-12-08 05:54 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +      Dialog.error('Error while adding a new member to the folder');
collaborator

2017-12-08 05:54 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +    let newMemberItem = document.createElement('P');
нужен CSS-класс, указывающий, что приглашение отправлено, ожидается подтверждение

2017-12-08 05:54 UTC, neSpecc commented on public/javascripts/folder-settings.js
> +    // TODO check if email is valid
надо запилить где-нибудь хелпер-метод

2017-12-08 22:41 UTC, talyguryn commented on controllers/directory.js
> +    ipcMain.on('folder - collaborator add', (event, {id, email}) => {
net

2017-12-08 22:41 UTC, talyguryn commented on models/directory.js
> +      // TODO send API request
нет

2017-12-08 22:41 UTC, talyguryn commented on public/javascripts/folder-settings.js
> +        email = input.value.trim(),
нет

2017-12-08 22:41 UTC, talyguryn commented on public/javascripts/folder-settings.js
> +    // TODO check if email is valid
надо

2017-12-08 22:41 UTC, talyguryn commented on public/javascripts/folder-settings.js
> +    let newMemberItem = document.createElement('P');
нужен

2017-12-09 02:08 UTC, neSpecc approved these changes

2017-12-09 02:15 UTC, gohabereg requested changes

2017-12-09 02:15 UTC, gohabereg commented on public/javascripts/folder-settings.js
> +    let newMemberItem = document.createElement('P');
Есть Dom. Сделай через него

2017-12-09 02:15 UTC, gohabereg commented on src/controllers/directory.js
> +   * @returns {Promise.<void>}
Это не соответствует действительности

2017-12-09 02:15 UTC, gohabereg commented on src/models/directory.js
> +      let dir = await db.insert(db.DIRECTORY, { 'name': name, 'notes': [], 'dt_update': dt_update } );
Вокруг ключей можно не ставить кавычки. Убери, пожалуйста

2017-12-09 02:15 UTC, gohabereg commented on src/models/users.js
> +    return await db.findOne(db.USER, { 'user': { $exists: true } });
И тут кавычки не нужны

2017-12-09 02:32 UTC, gohabereg approved these changes

2017-12-09 02:33 UTC, merged