send request to API to delete folder
codex-team/electon.editor pull request #96
Opened 2017-12-12 18:34 UTC by khaydarov

2017-12-12 19:34 UTC, neSpecc requested changes

2017-12-12 19:34 UTC, neSpecc commented on src/models/directory.js
> +      return deleteDirectoryResult & deleteNotesResult & ( deletedFromServer || true );
`deletedFromServer` не видна в этом скоупе

2017-12-12 21:03 UTC, gohabereg commented on src/models/directory.js
>          user: '' // @todo put here user's id
`global.user.id`, если не ошибаюсь

2017-12-13 21:23 UTC, neSpecc approved these changes

2017-12-14 17:25 UTC, talyguryn approved these changes

2017-12-14 17:25 UTC, talyguryn commented on src/models/directory.js
> +      if (process.env.DEBUG !== 'true') {
?

2017-12-14 17:25 UTC, talyguryn commented on src/models/directory.js
> +        user: global.user ? global.user.id : null
сервер вернет 500, если получит пустого пользователя

2017-12-14 17:26 UTC, talyguryn requested changes

2017-12-14 17:26 UTC, talyguryn commented on src/models/directory.js
> +      await isOnline().then(() => {
убери это в апи

2017-12-14 17:56 UTC, talyguryn approved these changes

2017-12-14 17:57 UTC, merged